### ISSUE TITLE
breaks on install

### ISSUE THREAD

**Issue by soniah** [b4hand/homebrew-bsdmainutils#1]
Thanks for writing this; I was installing it to get a proper `cal`. But it breaks on install:

```
% sw_vers -productVersion
10.10.5

% brew tap b4hand/bsdmainutils
==> Tapping b4hand/bsdmainutils
Cloning into '/usr/local/Library/Taps/b4hand/homebrew-bsdmainutils'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Tapped 1 formula (31 files, 132K)

% brew install bsdmainutils
Error: undefined method `desc' for Formulary::Formulae::Bsdmainutils:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/b4hand/homebrew-bsdmainutils/bsdmainutils.rb:2:in `<class:Bsdmainutils>'
/usr/local/Library/Taps/b4hand/homebrew-bsdmainutils/bsdmainutils.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by b4hand** [comment]
I'm running 10.10.5 as well, and I just uninstalled, untapped, retapped, and reinstalled on my local machine, and it seemingly builds cleanly.

Also, the [`desc` method](http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula#desc%3D-class_method) is a required method for a Formula, so the error message doesn't quite make sense to me.

**Comment by b4hand** [comment]
I should also mention that I am in fact defining `desc` on my Formula as well:

https://github.com/b4hand/homebrew-bsdmainutils/blob/master/bsdmainutils.rb#L2

**Comment by b4hand** [comment]
By the way, what version of brew are you running?

```
$ brew --version
Homebrew 0.9.5 (git revision bfc28; last commit 2015-12-16)
```

**Comment by soniah** [comment]
Well I got it to install correctly (after fixing up brew-cask following instructions at [1]). However after reinstalling homebrew-bsdmainutils I don't see `cal` in /usr/local/bin. Maybe it's my old xcode.

```
% pwd
/usr/local/bin

% ls -al | grep 7z 
lrwxr-xr-x    1 sonia  admin       29  8 Aug 19:38 7z -> ../Cellar/p7zip/9.20.1/bin/7z
lrwxr-xr-x    1 sonia  admin       30  8 Aug 19:38 7za -> ../Cellar/p7zip/9.20.1/bin/7za
lrwxr-xr-x    1 sonia  admin       30  8 Aug 19:38 7zr -> ../Cellar/p7zip/9.20.1/bin/7zr

% ls -al | grep cal
lrwxr-xr-x    1 root   admin       22 28 Apr  2015 aws -> /usr/local/aws/bin/aws
```

[1] http://apple.stackexchange.com/questions/218999/how-to-deal-with-commands-of-conflicting-names-listed-in-brew-doctor

Doesn't matter, I wrote my own script that's good enough for what I want:

```
#!/bin/bash                                                                         

case "$OSTYPE" in                                                                   
  solaris*) echo "SOLARIS" ;;                                                       

  darwin*)                                                                          
    case $# in                                                                      
      0) month=$(date +%m) year=$(date +%Y);;                                       
      2) month=$1 year=$2;;                                                         
      *) echo 1>&2 "Usage: $0 [MONTH YEAR]"; exit 3;;                               
    esac                                                                            

    month=${month#"${month%%[!0]*}"}                                                
    if ((month == 1)); then                                                         
      previous_month=12 previous_year=$((year-1))                                   
    else                                                                            
      previous_month=$((month-1)) previous_year=$year                               
    fi                                                                              

    if ((month == 12)); then                                                        
      next_month=1 next_year=$((year+1))                                            
    else                                                                            
      next_month=$((month+1)) next_year=$year                                       
    fi                                                                              

    paste <(cal $previous_month $previous_year) <(cal $month $year) <(cal $next_month $next_year)
    ;;                                                                              

  linux*)                                                                           
    ncal -3 -M -b                                                                   
    ;;                                                                              

  bsd*)     echo "BSD" ;;                                                           

  *)        echo "unknown: $OSTYPE" ;;                                              

esac 
```

Re-installing:

```
% brew --version
0.9.5

% brew update ; brew update ; brew doctor
Already up-to-date.
Already up-to-date.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (6.3) is outdated
Please update to Xcode 7.2.
Xcode can be updated from the App Store.

% brew untap b4hand/bsdmainutils
Untapping b4hand/bsdmainutils... (33 files, 140K)
Untapped 1 formula

% brew tap b4hand/bsdmainutils 
==> Tapping b4hand/bsdmainutils
Cloning into '/usr/local/Library/Taps/b4hand/homebrew-bsdmainutils'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Tapped 1 formula (31 files, 132K)
```
